### ISSUE TITLE
Wrong image url in sitemap

### ISSUE THREAD

**Issue by jcourtei** [mageplaza/magento-2-google-xml-sitemap#2]
In Model/Sitemap.php, _getMediaUrl() method is used and generates a wrong image url. This method is deprecated and should not be used anymore. Instead of
`htmlspecialchars($this->_getMediaUrl($image->getUrl()))`
just use
`htmlspecialchars($image->getUrl())`

_isEnabledSubmissionRobots() and _addSitemapToRobotsTxt() methods are also deprecated and will be removed.

**Comment by saunptit97** [comment]
Thank you for your feedback.
About the problem you mentioned. We highly appreciate any ideas, suggestions, and comments like yours and consider them in our next improvement to make our products better. Thank you very much!

**Comment by jaxtheking** [comment]
I just realised I am facing this same issue, one year and a half later.
Can I ask if there's any intention to implement this quick fix?
As pointed out by the OP, _getMediaUrl has been deprecated since 100.2.0 (No longer used, as we're generating product image URLs inside collection instead).

Thanks.
