### ISSUE TITLE
XML Sitemap limits to 4 links

### ISSUE THREAD

**Issue by vincentteyssier** [mageplaza/magento-2-google-xml-sitemap#8]
Hi,

I installed the extension on Magento 2.3.4.
Standard configuration, I have 6 pages, 4 categories, 6 products.
However the generated XML sitemap contains only 4 links.
No categories, no products, no 404 no enable-cookies or no homepage.

How do you get all pages in the xml sitemap ?

**Comment by Tuvpt** [comment]
Thank you for your interest in our product.
Please change Exclude Sitemap value in page, category, product in backend before you generate sitemap

**Comment by vincentteyssier** [comment]
Thanks for the answer. Quite surprising that your default value is Yes for exclusion though.... is it intended?

**Comment by Tuvpt** [comment]
the use of exclusions to avoid adding too many unnecessary products, categories, pages to the sitemap.

**Comment by vincentteyssier** [comment]
ok, looks a bit weird to me but ok, closing

**Comment by OvalMedia** [comment]
The default after installing this module is to exclude everything. This can hardly be intentional. Also as a user you are not notified of this issue. Moreover the attribute mp_exclude_sitemap has "No" as a default value which tells me the intention actually WAS to NOT exclude by default. 

I reported this back in 2019: https://github.com/mageplaza/magento-2-google-xml-sitemap/issues/5

In conclusion: there is an issue but none of the developers seem to care enough.
